### ISSUE TITLE
Get to 0.8.0

### ISSUE THREAD

**Issue by ryanzec** [ryanzec/nucleus-react#114]
This issue will track everything I feel is needed to get this project to 0.8.0 which will be the first version that I would not consider this framework to be experimental only type thing (though I would probably only consider it to be a pre-alpha / alpha). This is the list of items that need to be completed in order to be 0.8.0 ready:

- [x] alert / notification components #129 
- [x] badge components #126 
- [x] breadcrumb components #117 
- [x] button components #118 
- [x] card components #119 
- [x] code components #137 
- [x] define media queries #121 
- [x] form components #124 
- [x] grid components #125 
- [x] list components #127 
- [x] modal components #128 
- [x] overlay components #130 
- [x] popover / drop down / tooltip components #131 
- [x] progress bar components #132 
- [x] svg icon components #133 
- [x] tested in chrome #134
