### ISSUE TITLE
Get to 0.9.0

### ISSUE THREAD

**Issue by ryanzec** [ryanzec/nucleus-react#138]
This issue will track everything I feel is needed to get this project to 0.9.0 which will focus on simple implementations of more complex components and additional testing. This is the list of items that need to be completed in order to be 0.9.0 ready:

- [x] auto complete / tagging components #116 
- [x] date picker components #120 
- [x] add support for include individual file from npm install #140
- [x] image component #143
